[package]
name = "ghaladb"
version = "0.1.0"
authors = ["Matt Gathu <mattgathu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
bincode = "1"
serde = { version = "1", features = ["derive"] }
typed-builder = "0.9.1"
log = "0.4"
rand = "0.8"
glob = "0.3.1"
tap = "1.0.1"
serde_json = "1.0.107"
patricia_tree = { version = "0.6.3", features = ["serde"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
rand = "0.8"
env_logger = "0.10"
tempdir = "0.3.7"

[[bench]]
name = "db_benchmark"
harness = false
