[package]
name = "ghaladb"
version = "0.1.0"
authors = ["Matt Gathu <mattgathu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
bincode = "1.3"
serde = {"version" = "1", "features" = ["derive"]}
typed-builder = "0.9.1"
