on:
  push:
    branches:
      - 'main'
      - 'auto-releases'

name: Create Release 

jobs:
  create_release:
    name: Create Release

    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: "create release"
        run: |-
          bash .github/create_rel.sh
 
